configuration:
  backupStorageLocation:
    - name: aws
      provider: aws
      bucket: rock-solid-backups # Matches aws_s3_bucket.velero_backups
      default: true
      config:
        region: us-east-1
  volumeSnapshotLocation:
    - name: aws
      provider: aws
      config:
        region: us-east-1

initContainers:
  - name: velero-plugin-for-aws
    image: velero/velero-plugin-for-aws:v1.9.0
    volumeMounts:
      - mountPath: /target
        name: plugins

credentials:
  existingSecret: cloud-credentials
